env:
  es6: true
  browser: true
  commonjs: true
  node: true
  jest: true

extends: ['airbnb', 'prettier', 'prettier/react']

parser: 'babel-eslint'

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 6
  sourceType: module

plugins: ['prettier']

settings:
  react:
    version: '16'

globals:
  window: true
  document: true
  localStorage: true
  FormData: true
  FileReader: true
  Blob: true
  navigator: true

rules:
  react/jsx-filename-extension: [
    1,
    {
      extensions: ['.js', '.jsx']
    }
  ]
  react/prop-types: 0
  no-underscore-dangle: 0
  import/imports-first: ['error', 'absolute-first']
  import/newline-after-import: 'error'
  import/no-extraneous-dependencies: ['error', devDependencies: true]
