env:
  es6: true
  browser: true
  commonjs: true
  node: true
  jest: true

extends: ['airbnb', 'prettier', 'prettier/react']

parser: 'babel-eslint'

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 6
  sourceType: module

plugins: ['prettier']

settings:
  react:
    version: '16'

globals:
  window: true
  document: true
  localStorage: true
  FormData: true
  FileReader: true
  Blob: true
  navigator: true

rules:
  no-shadow: 'off'
  func-names: ['error', 'as-needed']
  no-underscore-dangle: 0
  react/require-default-props: [0, { forbidDefaultForRequired: true }]
  react/prop-types: 0
  react/jsx-filename-extension: [
    1,
    {
      extensions: ['.js', '.jsx']
    }
  ]
  react/forbid-prop-types: [0, { forbid: [''], checkContextTypes: false, checkChildContextTypes: false }]

  react/jsx-curly-spacing: ['error', 'never']
  react/sort-prop-types: [1, { callbacksLast: true, ignoreCase: true }]
  react/jsx-sort-props: [1, { callbacksLast: true, ignoreCase: true }]
  react/jsx-sort-default-props: [1, { ignoreCase: true }]
  react/jsx-boolean-value: 'never'

  import/no-named-as-default: 0
  import/prefer-default-export: 'off'
  import/imports-first: ['error', 'absolute-first']
  import/newline-after-import: 'error'
  import/no-extraneous-dependencies: ['error', devDependencies: true]
  jsx-a11y/no-noninteractive-tabindex: ['none']
  jsx-a11y/no-static-element-interactions: ['none']
  jsx-a11y/no-noninteractive-element-interactions: ['none']
  jsx-a11y/click-events-have-key-events: 'off'

