export const REQUEST_OFFERS = 'REQUEST_OFFERS';
export const RECEIVE_OFFERS = 'RECEIVE_OFFERS';
export const UPDATE_OFFERS = 'UPDATE_OFFERS';

export const ADD_OFFER_TO_FAVORITIES = 'ADD_OFFER_TO_FAVORITIES';
export const REMOVE_OFFER_FROM_FAVORITIES = 'REMOVE_OFFER_FROM_FAVORITIES';
