export const REQUEST_FAVORITE_OFFERS = 'REQUEST_FAVORITE_OFFERS';
export const RECEIVE_FAVORITE_OFFERS = 'RECEIVE_FAVORITE_OFFERS';

export const ADD_OFFER_TO_FAVORITIES = 'ADD_OFFER_TO_FAVORITIES';
export const REMOVE_OFFER_FROM_FAVORITIES = 'REMOVE_OFFER_FROM_FAVORITIES';
