export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';

export const BAD_REQUEST = 'BAD_REQUEST';
export const RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND';

export const REQUEST_SIGN_IN = 'REQUEST_SIGN_IN';
export const RECEIVE_SIGN_IN = 'RECEIVE_SIGN_IN';

export const TOOGLE_READY_APP = 'TOOGLE_READY_APP';
export const TOOGLE_AUTH_APP = 'TOOGLE_AUTH_APP';
